version: "3.8"
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: BlockEdu
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 131787
    ports:
      - "5432:5432"
    networks:
      - backend

  springboot-app:
    build: .
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}


    ports:
      - "8080:8080"
    networks:
      - backend

networks:
  backend:
